[package]
name = "tmp"
version = "0.1.0"
authors = ["Yuta123456 <yuuta09090530@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
