[package]
name = "abc050"
version = "0.1.0"
authors = ["Yuta123456 <yuuta09090530@icloud.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
